// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
 * buttonColor?: string // Button Color
 * text?: string // Text
 * textColor?: string // Text Color
 * pupilColor?: string // Pupil Color
 * eyeColor?: string // Eye Color
 * eyeCount?: 'One' | 'Two' // Eye Count
 * eyeSize(Px)?: number // Eye Size (Px)
 * pupilSize(Px)?: number // Pupil Size (Px)
 * eyeGap(Px)?: number // Eye Gap (Px)
 * speed?: number // Speed
 * range(%)?: number // Range (%)
 * blinking?: boolean // Blinking
 * blinkInterval?: number // Blink Interval
 * padding?: any // Padding
 * radius?: any // Radius
}} Props

 */
import { routes } from "./chunks/chunk-VG7AXKTA.js";

// virtual:eye-follow-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/CaDed4uVS4F4koHi8Ddp/UiZdcXLPs68fBczUfQ27/kYiayLQ5g.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getPropertyControls,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/5dCWb80pMX3rkZ6mTvF6/rPe7prLpTtzjXMR9Lynw/FollowEyes.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import { useEffect, useState, useRef, startTransition, useMemo } from "react";
import {
	addPropertyControls,
	ControlType,
	useIsStaticRenderer,
} from "unframer";
import { motion } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function FollowEyes(props) {
	const {
		eyeColor,
		pupilColor,
		eyeSize,
		pupilSize: rawPupilSize,
		eyeSpacing,
		trackingSpeed,
		trackingRange,
		eyeCount,
		enableBlinking,
		blinkInterval,
		style,
	} = props;
	const pupilSize = useMemo(
		() => Math.min(rawPupilSize, eyeSize * 0.8),
		[rawPupilSize, eyeSize],
	);
	const containerRef = useRef(null);
	const [leftPupilPos, setLeftPupilPos] = useState({
		x: 0,
		y: 0,
	});
	const [rightPupilPos, setRightPupilPos] = useState({
		x: 0,
		y: 0,
	});
	const [centerPupilPos, setCenterPupilPos] = useState({
		x: 0,
		y: 0,
	});
	const [isBlinking, setIsBlinking] = useState(false);
	const isStatic = useIsStaticRenderer();
	const maxDistance = useMemo(
		() => ((eyeSize - pupilSize) / 2) * (trackingRange / 100),
		[eyeSize, pupilSize, trackingRange],
	);
	useEffect(() => {
		if (isStatic || !enableBlinking) return;
		const blinkDuration = 200;
		const interval = setInterval(() => {
			startTransition(() => setIsBlinking(true));
			setTimeout(() => {
				startTransition(() => setIsBlinking(false));
			}, blinkDuration);
		}, blinkInterval);
		return () => clearInterval(interval);
	}, [isStatic, enableBlinking, blinkInterval]);
	useEffect(() => {
		if (isStatic) return;
		const handleMouseMove = (e) => {
			if (!containerRef.current) return;
			const rect = containerRef.current.getBoundingClientRect();
			const centerX = rect.left + rect.width / 2;
			const centerY = rect.top + rect.height / 2;
			const mouseX = e.clientX - centerX;
			const mouseY = e.clientY - centerY;
			if (eyeCount === "one") {
				const distance = Math.sqrt(mouseX * mouseX + mouseY * mouseY);
				if (distance === 0) {
					startTransition(() =>
						setCenterPupilPos({
							x: 0,
							y: 0,
						}),
					);
					return;
				}
				const clampedDistance = Math.min(distance, maxDistance);
				const angle = Math.atan2(mouseY, mouseX);
				startTransition(() => {
					setCenterPupilPos({
						x: Math.cos(angle) * clampedDistance,
						y: Math.sin(angle) * clampedDistance,
					});
				});
			} else {
				const leftEyeOffsetX = -eyeSpacing / 2;
				const rightEyeOffsetX = eyeSpacing / 2;
				const calculatePupilPosition = (eyeOffsetX) => {
					const relativeX = mouseX - eyeOffsetX;
					const relativeY = mouseY;
					const distance = Math.sqrt(
						relativeX * relativeX + relativeY * relativeY,
					);
					if (distance === 0)
						return {
							x: 0,
							y: 0,
						};
					const clampedDistance = Math.min(distance, maxDistance);
					const angle = Math.atan2(relativeY, relativeX);
					return {
						x: Math.cos(angle) * clampedDistance,
						y: Math.sin(angle) * clampedDistance,
					};
				};
				const leftPos = calculatePupilPosition(leftEyeOffsetX);
				const rightPos = calculatePupilPosition(rightEyeOffsetX);
				startTransition(() => {
					setLeftPupilPos(leftPos);
					setRightPupilPos(rightPos);
				});
			}
		};
		__unframerWindow.addEventListener("mousemove", handleMouseMove);
		return () =>
			__unframerWindow.removeEventListener("mousemove", handleMouseMove);
	}, [isStatic, eyeSpacing, maxDistance, eyeCount]);
	const containerWidth = useMemo(
		() => (eyeCount === "one" ? eyeSize : eyeSize * 2 + eyeSpacing),
		[eyeCount, eyeSize, eyeSpacing],
	);
	return (
		<div
			suppressHydrationWarning={true}
			ref={containerRef}
			style={{
				...style,
				backgroundColor: "transparent",
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
				gap: eyeCount === "two" ? eyeSpacing : 0,
				overflow: "visible",
				position: "relative",
				width: containerWidth,
				height: eyeSize,
			}}
		>
			{eyeCount === "one" ? (
				<div
					suppressHydrationWarning={true}
					style={{
						width: eyeSize,
						height: eyeSize,
						borderRadius: "50%",
						overflow: "hidden",
					}}
				>
					<motion.div
						suppressHydrationWarning={true}
						style={{
							width: eyeSize,
							height: eyeSize,
							borderRadius: "50%",
							backgroundColor: eyeColor,
							position: "relative",
							display: "flex",
							alignItems: "center",
							justifyContent: "center",
							transformOrigin: "center",
						}}
						animate={{
							scaleY: isBlinking ? 0.3 : 1,
						}}
						transition={{
							duration: 0.1,
							ease: "easeInOut",
						}}
					>
						<motion.div
							suppressHydrationWarning={true}
							style={{
								width: pupilSize,
								height: pupilSize,
								borderRadius: "50%",
								backgroundColor: pupilColor,
								opacity: isBlinking ? 0 : 1,
							}}
							animate={{
								x: centerPupilPos.x,
								y: centerPupilPos.y,
							}}
							transition={{
								type: "spring",
								stiffness: trackingSpeed,
								damping: 20,
							}}
						/>
					</motion.div>
				</div>
			) : (
				<_Fragment>
					<div
						suppressHydrationWarning={true}
						style={{
							width: eyeSize,
							height: eyeSize,
							borderRadius: "50%",
							overflow: "hidden",
						}}
					>
						<motion.div
							suppressHydrationWarning={true}
							style={{
								width: eyeSize,
								height: eyeSize,
								borderRadius: "50%",
								backgroundColor: eyeColor,
								position: "relative",
								display: "flex",
								alignItems: "center",
								justifyContent: "center",
								transformOrigin: "center",
							}}
							animate={{
								scaleY: isBlinking ? 0.3 : 1,
							}}
							transition={{
								duration: 0.1,
								ease: "easeInOut",
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								style={{
									width: pupilSize,
									height: pupilSize,
									borderRadius: "50%",
									backgroundColor: pupilColor,
									opacity: isBlinking ? 0 : 1,
								}}
								animate={{
									x: leftPupilPos.x,
									y: leftPupilPos.y,
								}}
								transition={{
									type: "spring",
									stiffness: trackingSpeed,
									damping: 20,
								}}
							/>
						</motion.div>
					</div>
					<div
						suppressHydrationWarning={true}
						style={{
							width: eyeSize,
							height: eyeSize,
							borderRadius: "50%",
							overflow: "hidden",
						}}
					>
						<motion.div
							suppressHydrationWarning={true}
							style={{
								width: eyeSize,
								height: eyeSize,
								borderRadius: "50%",
								backgroundColor: eyeColor,
								position: "relative",
								display: "flex",
								alignItems: "center",
								justifyContent: "center",
								transformOrigin: "center",
							}}
							animate={{
								scaleY: isBlinking ? 0.3 : 1,
							}}
							transition={{
								duration: 0.1,
								ease: "easeInOut",
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								style={{
									width: pupilSize,
									height: pupilSize,
									borderRadius: "50%",
									backgroundColor: pupilColor,
									opacity: isBlinking ? 0 : 1,
								}}
								animate={{
									x: rightPupilPos.x,
									y: rightPupilPos.y,
								}}
								transition={{
									type: "spring",
									stiffness: trackingSpeed,
									damping: 20,
								}}
							/>
						</motion.div>
					</div>
				</_Fragment>
			)}
		</div>
	);
}
addPropertyControls(FollowEyes, {
	eyeCount: {
		type: ControlType.Enum,
		title: "Eye Count",
		options: ["one", "two"],
		optionTitles: ["One", "Two"],
		defaultValue: "two",
		displaySegmentedControl: true,
		description: "Number of eyes (1 or 2).",
	},
	eyeColor: {
		type: ControlType.Color,
		title: "Eye Color",
		defaultValue: "#FFFFFF",
		description: "Color of the eye background.",
	},
	pupilColor: {
		type: ControlType.Color,
		title: "Pupil Color",
		defaultValue: "#000000",
		description: "Color of the pupil.",
	},
	eyeSize: {
		type: ControlType.Number,
		title: "Eye Size",
		defaultValue: 120,
		min: 10,
		max: 300,
		step: 1,
		unit: "px",
		description: "Overall size of the eye shape in pixels (px).",
	},
	pupilSize: {
		type: ControlType.Number,
		title: "Pupil Size",
		defaultValue: 40,
		min: 10,
		max: 100,
		step: 1,
		unit: "px",
		description: "Size of the pupil inside the eye in pixels (px).",
	},
	eyeSpacing: {
		type: ControlType.Number,
		title: "Eye Gap",
		defaultValue: 40,
		min: 0,
		max: 200,
		step: 1,
		unit: "px",
		hidden: ({ eyeCount }) => eyeCount === "one",
		description: "Space between the two eyes in pixels (px) when using 2 eyes.",
	},
	trackingSpeed: {
		type: ControlType.Number,
		title: "Speed",
		defaultValue: 150,
		min: 50,
		max: 500,
		step: 10,
		unit: "stiffness",
		description:
			"How quickly the eyes follow the cursor (higher stiffness = faster, unitless).",
	},
	trackingRange: {
		type: ControlType.Number,
		title: "Range",
		defaultValue: 80,
		min: 0,
		max: 100,
		step: 5,
		unit: "%",
		description:
			"How far the pupils can move inside the eye as a percentage (%).",
	},
	enableBlinking: {
		type: ControlType.Boolean,
		title: "Blinking",
		defaultValue: true,
		enabledTitle: "On",
		disabledTitle: "Off",
		description: "Turn blinking animation on or off.",
	},
	blinkInterval: {
		type: ControlType.Number,
		title: "Blink Interval",
		defaultValue: 3e3,
		min: 500,
		max: 1e4,
		step: 100,
		unit: "ms",
		hidden: ({ enableBlinking }) => !enableBlinking,
		description: "How often the eye blinks in milliseconds (ms).",
	},
});

// /:https://framerusercontent.com/modules/CaDed4uVS4F4koHi8Ddp/UiZdcXLPs68fBczUfQ27/kYiayLQ5g.js
var FollowEyesFonts = getFonts(FollowEyes);
var FollowEyesControls = getPropertyControls(FollowEyes);
var serializationHash = "framer-uKWHf";
var variantClassNames = {
	H4taCltct: "framer-v-mh7fy",
};
var numberToPixelString = (value) => {
	if (typeof value !== "number") return value;
	if (!Number.isFinite(value)) return void 0;
	return Math.max(0, value) + "px";
};
var radiusForCorner = (value, cornerIndex) => {
	if (typeof value === "number" && Number.isFinite(value))
		return Math.max(0, value) + "px";
	if (typeof value !== "string" || typeof cornerIndex !== "number")
		return void 0;
	const segments = value.split(" ");
	return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var humanReadableEnumMap = {
	One: "one",
	Two: "two",
};
var getProps = ({
	blinking,
	blinkInterval,
	buttonColor,
	eyeColor,
	eyeCount,
	eyeGapPx,
	eyeSizePx,
	height,
	id,
	link,
	padding,
	pupilColor,
	pupilSizePx,
	radius,
	range,
	speed,
	text,
	textColor,
	width,
	...props
}) => {
	return {
		...props,
		AmmV7xj6g: eyeSizePx ?? props.AmmV7xj6g ?? 40,
		BgmIAzzRV: radius ?? props.BgmIAzzRV ?? "30px",
		DbOmokZP0: textColor ?? props.DbOmokZP0 ?? "rgb(255, 255, 255)",
		EDzxvbp5Q: padding ?? props.EDzxvbp5Q ?? "6px 6px 6px 20px",
		F9xEnRksX:
			humanReadableEnumMap[eyeCount] ?? eyeCount ?? props.F9xEnRksX ?? "two",
		Ftd7ea6ZK: range ?? props.Ftd7ea6ZK ?? 90,
		GmXdHB9SX: blinking ?? props.GmXdHB9SX,
		h_OXotjfD: pupilSizePx ?? props.h_OXotjfD ?? 12,
		LWV7WvkSz: eyeColor ?? props.LWV7WvkSz ?? "rgb(255, 255, 255)",
		n7FNYiflu: blinkInterval ?? props.n7FNYiflu ?? 2e3,
		ooNLd407F: speed ?? props.ooNLd407F ?? 100,
		qcTsc8aEM: text ?? props.qcTsc8aEM ?? "Get in touch",
		qNjswW_Tg: link ?? props.qNjswW_Tg,
		s8XHH4TvL: eyeGapPx ?? props.s8XHH4TvL ?? 4,
		ucHarSLTi: buttonColor ?? props.ucHarSLTi ?? "rgb(0, 0, 0)",
		Z_ma24kbm: pupilColor ?? props.Z_ma24kbm ?? "rgb(0, 0, 0)",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		qNjswW_Tg: qNjswW_Tg2,
		ucHarSLTi: ucHarSLTi2,
		qcTsc8aEM: qcTsc8aEM2,
		DbOmokZP0: DbOmokZP02,
		Z_ma24kbm: Z_ma24kbm2,
		LWV7WvkSz: LWV7WvkSz2,
		F9xEnRksX: F9xEnRksX2,
		AmmV7xj6g: AmmV7xj6g2,
		h_OXotjfD: h_OXotjfD2,
		s8XHH4TvL: s8XHH4TvL2,
		ooNLd407F: ooNLd407F2,
		Ftd7ea6ZK: Ftd7ea6ZK2,
		GmXdHB9SX: GmXdHB9SX2,
		n7FNYiflu: n7FNYiflu2,
		EDzxvbp5Q: EDzxvbp5Q2,
		BgmIAzzRV: BgmIAzzRV2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "H4taCltct",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<Link
						suppressHydrationWarning={true}
						href={qNjswW_Tg2}
						nodeId={"H4taCltct"}
						openInNewTab={false}
					>
						<motion2.a
							suppressHydrationWarning={true}
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-mh7fy", className, classNames)} framer-2mr8ng`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"H4taCltct"}
							ref={refBinding}
							style={{
								"--eetrnf": numberToPixelString(EDzxvbp5Q2),
								backgroundColor: ucHarSLTi2,
								borderBottomLeftRadius: radiusForCorner(BgmIAzzRV2, 3),
								borderBottomRightRadius: radiusForCorner(BgmIAzzRV2, 2),
								borderTopLeftRadius: radiusForCorner(BgmIAzzRV2, 0),
								borderTopRightRadius: radiusForCorner(BgmIAzzRV2, 1),
								boxShadow:
									"0.39809593676181976px 0.39809593676181976px 0.5629926728941875px -0.3125px rgba(0, 0, 0, 0.07), 1.207253071552259px 1.207253071552259px 1.7073136670057811px -0.625px rgba(0, 0, 0, 0.08), 3.1913267607422307px 3.1913267607422307px 4.51321758700586px -0.9375px rgba(0, 0, 0, 0.1), 10px 10px 14.142135623730951px -1.25px rgba(0, 0, 0, 0.19)",
								...style,
							}}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-nym2w0"}
								data-framer-name={"Text"}
								fonts={["FS;Manrope-bold"]}
								layoutDependency={layoutDependency}
								layoutId={"iS5vKmVCC"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-DbOmokZP0-kYiayLQ5g)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--variable-reference-DbOmokZP0-kYiayLQ5g": DbOmokZP02,
								}}
								text={qcTsc8aEM2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion2.p
										suppressHydrationWarning={true}
										style={{
											"--font-selector": "RlM7TWFucm9wZS1ib2xk",
											"--framer-font-family":
												'"Manrope", "Manrope Placeholder", sans-serif',
											"--framer-font-weight": "700",
											"--framer-letter-spacing": "-0.02em",
											"--framer-line-height": "1.4em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-DbOmokZP0-kYiayLQ5g))",
										}}
									>
										{"Get in touch"}
									</motion2.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider suppressHydrationWarning={true}>
								<SmartComponentScopedContainer
									suppressHydrationWarning={true}
									className={"framer-3e0xtv-container"}
									data-code-component-plugin-id={"84d4c1"}
									isAuthoredByUser={true}
									layoutDependency={layoutDependency}
									layoutId={"SipBS9ALL-container"}
									nodeId={"SipBS9ALL"}
									rendersWithMotion={true}
									scopeId={"kYiayLQ5g"}
								>
									<FollowEyes
										suppressHydrationWarning={true}
										blinkInterval={n7FNYiflu2}
										enableBlinking={GmXdHB9SX2}
										eyeColor={LWV7WvkSz2}
										eyeCount={F9xEnRksX2}
										eyeSize={AmmV7xj6g2}
										eyeSpacing={s8XHH4TvL2}
										height={"100%"}
										id={"SipBS9ALL"}
										layoutId={"SipBS9ALL"}
										pupilColor={Z_ma24kbm2}
										pupilSize={h_OXotjfD2}
										style={{
											height: "100%",
											width: "100%",
										}}
										trackingRange={Ftd7ea6ZK2}
										trackingSpeed={ooNLd407F2}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion2.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-uKWHf.framer-2mr8ng, .framer-uKWHf .framer-2mr8ng { display: block; }",
	".framer-uKWHf.framer-mh7fy { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: var(--eetrnf); position: relative; text-decoration: none; width: min-content; }",
	".framer-uKWHf .framer-nym2w0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-uKWHf .framer-3e0xtv-container { flex: none; height: auto; position: relative; width: auto; }",
];
var FramerkYiayLQ5g = withCSS(Component, css, "framer-uKWHf");
var stdin_default = FramerkYiayLQ5g;
FramerkYiayLQ5g.displayName = "Eye Follow Button";
FramerkYiayLQ5g.defaultProps = {
	height: 52,
	width: 221,
};
addPropertyControls2(FramerkYiayLQ5g, {
	qNjswW_Tg: {
		title: "Link",
		type: ControlType2.Link,
	},
	ucHarSLTi: {
		defaultValue: "rgb(0, 0, 0)",
		title: "Button Color",
		type: ControlType2.Color,
	},
	qcTsc8aEM: {
		defaultValue: "Get in touch",
		displayTextArea: false,
		title: "Text",
		type: ControlType2.String,
	},
	DbOmokZP0: {
		defaultValue: "rgb(255, 255, 255)",
		title: "Text Color",
		type: ControlType2.Color,
	},
	Z_ma24kbm: {
		defaultValue: "rgb(0, 0, 0)",
		title: "Pupil Color",
		type: ControlType2.Color,
	},
	LWV7WvkSz: {
		defaultValue: "rgb(255, 255, 255)",
		title: "Eye Color",
		type: ControlType2.Color,
	},
	F9xEnRksX: FollowEyesControls?.["eyeCount"] && {
		...FollowEyesControls["eyeCount"],
		defaultValue: "two",
		description: void 0,
		hidden: void 0,
		title: "Eye Count",
	},
	AmmV7xj6g: {
		defaultValue: 40,
		max: 300,
		min: 10,
		step: 1,
		title: "Eye Size (Px)",
		type: ControlType2.Number,
	},
	h_OXotjfD: {
		defaultValue: 12,
		max: 100,
		min: 1,
		step: 1,
		title: "Pupil Size (Px)",
		type: ControlType2.Number,
	},
	s8XHH4TvL: {
		defaultValue: 4,
		max: 200,
		min: 0,
		step: 1,
		title: "Eye Gap (Px)",
		type: ControlType2.Number,
	},
	ooNLd407F: {
		defaultValue: 100,
		max: 500,
		min: 50,
		step: 10,
		title: "Speed",
		type: ControlType2.Number,
	},
	Ftd7ea6ZK: {
		defaultValue: 90,
		max: 100,
		min: 0,
		step: 5,
		title: "Range (%)",
		type: ControlType2.Number,
	},
	GmXdHB9SX: {
		defaultValue: false,
		title: "Blinking",
		type: ControlType2.Boolean,
	},
	n7FNYiflu: {
		defaultValue: 2e3,
		max: 1e4,
		min: 500,
		step: 100,
		title: "Blink Interval",
		type: ControlType2.Number,
	},
	EDzxvbp5Q: {
		defaultValue: "6px 6px 6px 20px",
		title: "Padding",
		type: ControlType2.Padding,
	},
	BgmIAzzRV: {
		defaultValue: "30px",
		title: "Radius",
		type: ControlType2.BorderRadius,
	},
});
addFonts(
	FramerkYiayLQ5g,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Manrope",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Manrope",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NGBUP45ES3F7RD5XGKPEDJ6QEPO4TMOK/EXDVWJ2EDDVVV65UENMX33EDDYBX6OF7/6P4FPMFQH7CCC7RZ4UU4NKSGJ2RLF7V5.woff2",
					weight: "700",
				},
			],
		},
		...FollowEyesFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:eye-follow-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders EyeFollowButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var eye_follow_button_default = ComponentWithRoot;
export { eye_follow_button_default as default };
